kernel:
  image: linuxkit/kernel:5.15.27-arm64
  cmdline: "console=ttyAMA0 console=tty0 console=tty1 linuxkit.unified_cgroup_hierarchy=1"
init:
  - linuxkit/init:14df799bb3b9e0eb0491da9fda7f32a108a2e2a5
  - linuxkit/runc:436357ce16dd663e24f595bcec26d5ae476c998e
  - linuxkit/containerd:eeb3aaf497c0b3f6c67f3a245d61ea5a568ca718
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
  - linuxkit/firmware:a17106a98940006529c714a3783eb03238c335a7
onboot:
  - name: modprobe
    image: linuxkit/modprobe:5dd4d7238f760bcd9f91b9166f414da953242f43
    command: ["modprobe", "nicvf"]
  - name: sysctl
    image: linuxkit/sysctl:e5959517fab7b44692ad63941eecf37486e73799
  - name: rngd1
    image: linuxkit/rngd:331294919ba6d953d261a2694019b659a98535a4
    command: ["/sbin/rngd", "-1"]
  - name: sysfs
    image: linuxkit/sysfs:4f58a2447d328d391143984fc4e8508b00dc6e5b
  - name: vlan
    image: linuxkit/ip:6cc44dd4e18ddb02de01bc4b34b5799971b6a7bf
    binds.add:
      - /etc/ip/vlan.sh:/etc/ip/vlan.sh
    command: ["/etc/ip/vlan.sh"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/etc/ip/dhcp.sh", "true"]
    binds.add:
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run:/run
      - /etc/ip/dhcp.sh:/etc/ip/dhcp.sh
      - /dhcpcd.conf:/dhcpcd.conf
    runtime:
      mkdir:
        - /var/lib/dhcpcd
services:
  - name: getty
    image: linuxkit/getty:06f34bce0facea79161566d67345c3ea49965437
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:331294919ba6d953d261a2694019b659a98535a4
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/etc/ip/dhcp.sh", "false"]
    binds.add:
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run:/run
      - /etc/ip/dhcp.sh:/etc/ip/dhcp.sh
      - /dhcpcd.conf:/dhcpcd.conf
    runtime:
      mkdir:
        - /var/lib/dhcpcd
  - name: ntpd
    image: linuxkit/openntpd:dd353cac6cbd816008c565041cec6650090d0ad0
  - name: hook-docker
    image: quay.io/tinkerbell/hook-docker:latest
    capabilities:
      - all
    net: host
    pid: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /dev/console:/dev/console
      - /dev:/dev
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /var/run/docker:/var/run
      - /var/run/images:/var/lib/docker
      - /var/run/worker:/worker
    runtime:
      mkdir:
        - /var/run/images
        - /var/run/docker
        - /var/run/worker

  - name: hook-bootkit
    image: quay.io/tinkerbell/hook-bootkit:latest
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw", "nosuid", "noexec", "nodev", "relatime"]
    binds:
      - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker
  - name: sshd
    image: linuxkit/sshd:62036c2a279715d05e8298b9269a0659964f2619
    binds.add:
      - /root/.ssh:/root/.ssh
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: etc/profile.d/local.sh
    contents: |
      alias       docker='ctr -n services.linuxkit tasks exec --tty --exec-id cmd hook-docker docker'
      alias docker-shell='ctr -n services.linuxkit tasks exec --tty --exec-id shell hook-docker sh'
    mode: "0644"

  - path: etc/ip/vlan.sh
    source: "files/vlan.sh"
    mode: "0777"

  - path: etc/ip/dhcp.sh
    source: "files/dhcp.sh"
    mode: "0777"

  - path: dhcpcd.conf
    source: "files/dhcpcd.conf"
    mode: "0644"
